a1.sources=i1 i2 i3
a1.channels=c1 c2 c3 c4 c5 c6
a1.sinks=o1 o2 o3 o4 o5 o6

a1.sources.i1.type=exec
a1.sources.i1.command=tail -F /data_log/sensor_raw.log
a1.sources.i1.batchSize=1000
a1.sources.i1.channels=c1 c2

a1.sources.i2.type=exec
a1.sources.i2.command=tail -F /data_log/log_raw.log
a1.sources.i2.batchSize=1000
a1.sources.i2.channels=c3 c4

a1.sources.i3.type=exec
a1.sources.i3.command=tail -F /data_log/2026-04-01@02:33-changerecord.csv
a1.sources.i3.batchSize=1000
a1.sources.i3.channels=c5 c6

a1.channels.c1.type=memory
a1.channels.c1.capacity=100000
a1.channels.c1.transactionCapacity=10000

a1.channels.c2.type=memory
a1.channels.c2.capacity=100000
a1.channels.c2.transactionCapacity=10000

a1.channels.c3.type=memory
a1.channels.c3.capacity=100000
a1.channels.c3.transactionCapacity=10000

a1.channels.c4.type=memory
a1.channels.c4.capacity=100000
a1.channels.c4.transactionCapacity=10000

a1.channels.c5.type=memory
a1.channels.c5.capacity=100000
a1.channels.c5.transactionCapacity=10000

a1.channels.c6.type=memory
a1.channels.c6.capacity=100000
a1.channels.c6.transactionCapacity=10000

a1.sinks.o1.type=org.apache.flume.sink.kafka.KafkaSink
a1.sinks.o1.kafka.topic=sensor_raw
a1.sinks.o1.kafka.bootstrap.servers=bigdata1:9092
a1.sinks.o1.kafka.flumeBatchSize=1000
a1.sinks.o1.kafka.producer.acks=1
a1.sinks.o1.kafka.producer.linger.ms=5
a1.sinks.o1.kafka.producer.compression.type=snappy
a1.sinks.o1.channel=c1

a1.sinks.o2.type=hdfs
a1.sinks.o2.hdfs.path=hdfs://bigdata1:9000/user/ods/sensor-raw
a1.sinks.o2.hdfs.filePrefix=sensor-raw-
a1.sinks.o2.hdfs.fileType=DataStream
a1.sinks.o2.hdfs.writeFormat=text
a1.sinks.o2.hdfs.useLocalTimeStamp=true
a1.sinks.o2.hdfs.rollInterval=30
a1.sinks.o2.hdfs.rollSize=1048576
a1.sinks.o2.hdfs.rollCount=0
a1.sinks.o2.hdfs.batchSize=1000
a1.sinks.o2.channel=c2

a1.sinks.o3.type=org.apache.flume.sink.kafka.KafkaSink
a1.sinks.o3.kafka.topic=log_raw
a1.sinks.o3.kafka.bootstrap.servers=bigdata1:9092
a1.sinks.o3.kafka.flumeBatchSize=1000
a1.sinks.o3.kafka.producer.acks=1
a1.sinks.o3.kafka.producer.linger.ms=5
a1.sinks.o3.kafka.producer.compression.type=snappy
a1.sinks.o3.channel=c3

a1.sinks.o4.type=hdfs
a1.sinks.o4.hdfs.path=hdfs://bigdata1:9000/user/ods/log-raw
a1.sinks.o4.hdfs.filePrefix=log-raw
a1.sinks.o4.hdfs.fileType=DataStream
a1.sinks.o4.hdfs.writeFormat=text
a1.sinks.o4.hdfs.useLocalTimeStamp=true
a1.sinks.o4.hdfs.rollInterval=30
a1.sinks.o4.hdfs.rollSize=1048576
a1.sinks.o4.hdfs.rollCount=0
a1.sinks.o4.hdfs.batchSize=1000
a1.sinks.o4.channel=c4

a1.sinks.o5.type=org.apache.flume.sink.kafka.KafkaSink
a1.sinks.o5.kafka.topic=ChangeRecord
a1.sinks.o5.kafka.bootstrap.servers=bigdata1:9092
a1.sinks.o5.kafka.flumeBatchSize=1000
a1.sinks.o5.kafka.producer.acks=1
a1.sinks.o5.kafka.producer.linger.ms=5
a1.sinks.o5.kafka.producer.compression.type=snappy
a1.sinks.o5.channel=c5

a1.sinks.o6.type=hdfs
a1.sinks.o6.hdfs.path=hdfs://bigdata1:9000/user/ods/change-record
a1.sinks.o6.hdfs.filePrefix=change-record
a1.sinks.o6.hdfs.fileType=DataStream
a1.sinks.o6.hdfs.writeFormat=text
a1.sinks.o6.hdfs.useLocalTimeStamp=true
a1.sinks.o6.hdfs.rollInterval=30
a1.sinks.o6.hdfs.rollSize=1048576
a1.sinks.o6.hdfs.rollCount=0
a1.sinks.o6.hdfs.batchSize=1000
a1.sinks.o6.channel=c6
