mysql.url=jdbc:mysql://master:3306/shtd_industry?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
mysql.username=root
mysql.password=123456

hdfs.url=hdfs://master:9000

# Hive ??
#hive.url=jdbc:hive2://master:10000/default
#hive.user=root
#hive.password=123456

# Spark ??
spark.master=local[*]
spark.serializer=org.apache.spark.serializer.KryoSerializer

# XGBoost ????
xgboost.fault.model.path=hdfs://master:9000/models/fault_probability_xgboost_v2
xgboost.rul.model.path=hdfs://master:9000/models/device_rul_xgboost_v1
xgboost.feature.table=dwd_environment_features
